[[main]]
  name = "Writeups"
  pageRef = "writeups"
  weight = 10

[[main]]
  name = "About"
  pageRef = "about"
  weight = 20

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 30

[[main]]
  name = "Categories"
  pageRef = "categories"
  weight = 40

[[main]]
  name = "GitHub"
  pre = "github"
  url = "https://github.com/k1nt4r0u"
  weight = 50

[[footer]]
  name = "Writeups"
  pageRef = "writeups"
  weight = 10

[[footer]]
  name = "About"
  pageRef = "about"
  weight = 20

[[footer]]
  name = "GitHub"
  url = "https://github.com/k1nt4r0u"
  weight = 30
